# Generated by Django 3.2.7 on 2021-09-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_input_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='input_values',
            field=models.TextField(),
        ),
    ]
